name: grape
channels:
  - defaults
dependencies:
  - pip=19.2.3
  - python=3.7.4
  - matplotlib=3.1.1
  - numpy=1.17.2
  - pip:
    - pyqt5==5.13.1
    - scipy==1.3.1
    - fancyimpute
    - seaborn # for plot
    # torch doesn't intall correctly
    # do this manually
    # torch and torchvision (https://pytorch.org/)
    # torch-geometric (https://github.com/rusty1s/pytorch_geometric)

